on:
  push:
    branches:
    - main
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest'] # 'windows-latest' // TODO: why does it break scala-cli?
        jvm: ['temurin:21', 'temurin:11']
    steps:
      - uses: actions/checkout@v4
      - uses: VirtusLab/scala-cli-setup@main
        with:
          jvm: ${{ matrix.jvm }}
      - run: scala-cli test .
