on:
  pull_request:

jobs:
  scalafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: VirtusLab/scala-cli-setup@main
        with:
          jvm: temurin:21
      - run: scala-cli format --check .
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: VirtusLab/scala-cli-setup@main
        with:
          jvm: temurin:21
      - run: ./scripts/updateLicense.sc